import ReactQueryProvider from "@/lib/react-query/react-query-provider";
import {
  ActionIcon,
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";
import { PawPrint, Settings2 } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <ReactQueryProvider>
          <MantineProvider defaultColorScheme="dark">
            <ModalsProvider>
              {" "}
              <header className="bg-background/95 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 mb-4 flex w-full backdrop-blur">
                <div className="mx-auto flex h-14 w-full max-w-screen-xl items-center md:px-8">
                  <div className="mr-4 hidden md:flex">
                    <Link
                      href={"/"}
                      className="mr-4 flex items-center space-x-2 lg:mr-6"
                    >
                      <PawPrint className="scale-x-[-1]" />
                      <span className="hidden font-bold lg:inline-block">
                        pulldog
                      </span>
                    </Link>
                  </div>
                  <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
                    <nav className="flex items-center">
                      <Link href={"/settings"}>
                        <ActionIcon
                          variant="subtle"
                          color="gray"
                          size="lg"
                          radius="xl"
                        >
                          <Settings2 size={16} />
                        </ActionIcon>
                      </Link>
                    </nav>
                  </div>
                </div>
              </header>
              {children}
            </ModalsProvider>
          </MantineProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
